In [5]:
import os

import jax
import jax.numpy as jnp

# Hardware setup
print("JAX version:", jax.__version__)
devices = jax.devices()
print("Available devices:")
for d in devices:
  print(d)

#jax.config.update("jax_platform_name", "gpu") # Make sure we're using the GPU
#jax.config.update("jax_enable_x64", True) # Make sure the highest precision is enabled in case we need
#jax.config.update("jax_default_matmul_precision", "bfloat16") # Set the default precision for matrix multiplication

#os.environ["NVIDIA_TF32_OVERRIDE"] = "1"
#os.environ["JAX_ENABLE_X64"] = "False"

print("Using device:", jax.default_backend())  # Should print 'gpu'

JAX version: 0.4.33
Available devices:
TPU_0(process=0,(0,0,0,0))
TPU_1(process=0,(0,0,0,1))
TPU_2(process=0,(1,0,0,0))
TPU_3(process=0,(1,0,0,1))
TPU_4(process=0,(0,1,0,0))
TPU_5(process=0,(0,1,0,1))
TPU_6(process=0,(1,1,0,0))
TPU_7(process=0,(1,1,0,1))
Using device: tpu


## Distributed Computation

In [6]:
def f(x):
    return x ** 2

x = jnp.arange(32).reshape(8, 4)
pmap_f = jax.pmap(f)

y = pmap_f(x)
print(y)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]
 [256 289 324 361]
 [400 441 484 529]
 [576 625 676 729]
 [784 841 900 961]]


## Distributed Training

In [7]:
@jax.pmap
def forward_pass(x):
    return jax.nn.relu(x)

x = jnp.ones((8, 128))  # 8 examples
y = forward_pass(x)
print(y.shape)

(8, 128)


### Test Devices
